version: '3.8'

services:
  web:
    # restart: always
    image: brodagroupsoftware/physrisk-api:latest
    ports:
      # - 8081:8081
      - 5000:8081
    environment:
        OSC_TEST_USER_KEY: ${OSC_TEST_USER_KEY}
        OSC_S3_ACCESS_KEY: ${OSC_S3_ACCESS_KEY}
        OSC_S3_SECRET_KEY: ${OSC_S3_SECRET_KEY}
        OSC_S3_BUCKET: ${OSC_S3_BUCKET}

  nginx:
    restart: always
    build: ./nginx
    container_name: nginx
    ports:
      - "8443:8443"
    depends_on:
      - web
